# 1 
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
import numpy as np

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
cov = (zp*ks).mean() - zp.mean() * ks.mean()
cov

9157.839999999997

In [5]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [7]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [8]:
np.cov(zp, ks, ddof=0) / (zp.std()*ks.std())

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

# 2
Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [18]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
sigma = iq.std(ddof=1)
iq_mean = iq.mean()

$\overline{X} \pm t_{\alpha/2} * \frac{\sigma_н}{\sqrt{n}}$, $\alpha = 0.05$, $n = 10$, $t_{\alpha/2} = 2,262$

In [20]:
print([iq_mean - 2.262 * sigma / (10**0.5), iq_mean + 2.262 * sigma / (10**0.5)])

[110.55660776308164, 125.64339223691834]


# 3
Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

$\overline{X} \pm Z_{\alpha/2} * \frac{\sigma}{\sqrt{n}}$

$D=25 -> sigma=5, n=27, \overline{X}=174.2, \alpha=0.05, Z_{\alpha/2} = 1.96$

In [23]:
print([174.2 - 1.96 * 5 / (27**0.5), 174.2 + 1.96 * 5 / (27**0.5)])

[172.31398912064722, 176.08601087935276]
